version: '3.9'
services:
  cassandra:
    image: cassandra:3.11
    ports:
      - '9042:9042'

  temporal:
    image: temporalio/auto-setup:1.21.1
    environment:
      - CASSANDRA_SEEDS=cassandra 
    depends_on:
      - cassandra
    ports:
      - '7233:7233'